apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-dmz
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: '-9' }
spec:
  project: platform
  destination:
    namespace: traefik-dmz
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 37.0.0
    helm:
      values: |
        podLabels:
          egress.zone: dmz

        ingressClass:
          enabled: true
          isDefaultClass: false
          name: dmz

        service:
          type: LoadBalancer
          annotations:
            lbipam.cilium.io/ips: '192.168.4.240'
          spec:
            loadBalancerClass: io.cilium/l2-announcer
            externalTrafficPolicy: Local

        deployment:
          kind: DaemonSet

        persistence:
          enabled: false

        tolerations:
          - key: "node-role.kubernetes.io/control-plane"
            operator: "Exists" # deploy on control-plane nodes
            effect: "NoSchedule"

        # ➜ Prometheus metrics & ServiceMonitor
        metrics:
          prometheus:
            enabled: true
            entryPoint: metrics
        ports:
          metrics:
            port: 9100
            expose:
              default: true
        serviceMonitor:
          enabled: true
          namespace: monitoring

        # ➜ JSON logs to Loki
        logs:
          general:
            format: json
          access:
            enabled: true
            format: json

        podSecurityContext:
          seccompProfile: { type: RuntimeDefault }

        securityContext:
          runAsUser: 65532
          runAsGroup: 65532
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities: { drop: ['ALL'] }
          seccompProfile: { type: RuntimeDefault }

        additionalArguments:
          - '--entrypoints.web.http.redirections.entrypoint.to=websecure'
          - '--entrypoints.web.http.redirections.entrypoint.scheme=https'
          - '--providers.kubernetescrd.ingressclass=dmz'
          - '--providers.kubernetesingress.ingressclass=dmz'

    syncOptions: ['CreateNamespace=true']
