apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: letsencrypt-dns
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: '-19' } # after cert-manager (-30), before dmz (-9)
spec:
  project: platform
  destination:
    { server: https://kubernetes.default.svc, namespace: cert-manager }
  source:
    repoURL: https://github.com/greg-court/homelab.git
    targetRevision: main
    path: k8s/gitops/apps/letsencrypt-dns/overlays/klab
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - PruneLast=true
