apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - netshoot-daemonset.yaml
  - netshoot-greg.yaml
  - netshoot-fam.yaml
  - netshoot-dmz.yaml
  - netshoot-trust.yaml
