apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: '-3' }
spec:
  project: platform
  destination: { server: https://kubernetes.default.svc, namespace: monitoring }
  source:
    repoURL: https://github.com/greg-court/homelab.git
    targetRevision: main
    path: k8s/gitops/apps/alloy/overlays/klab
