apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kps-extras
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: '-4' } # alongside Loki/KPS
spec:
  project: platform
  destination: { namespace: monitoring }
  source:
    repoURL: https://github.com/greg-court/homelab.git
    targetRevision: main
    path: k8s/gitops/apps/monitoring/kps/overlays/klab
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
