apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: expose-hubble
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: '10' }
spec:
  project: platform
  destination: { namespace: kube-system }
  source:
    repoURL: https://github.com/greg-court/homelab.git
    targetRevision: main
    path: k8s/gitops/apps/expose-hubble/overlays/klab
