apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vip-pbr
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: '-8' } # after CNI/LB, before apps
spec:
  project: platform
  destination:
    namespace: kube-system
  source:
    repoURL: https://github.com/greg-court/homelab.git
    targetRevision: main
    path: k8s/gitops/apps/vip-pbr
