apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unifi-tls-cert
  namespace: net
spec:
  secretName: unifi-tls
  dnsNames: ['unifi.infra.klab.internal']
  issuerRef: { kind: ClusterIssuer, name: homelab-ca }
