apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: adguard-home-tls-cert
  namespace: adguard
spec:
  secretName: adguard-home-tls
  dnsNames:
    - adguardhome.infra.klab.internal
    - adguardhome.apps.klab.internal
  issuerRef:
    kind: ClusterIssuer
    name: homelab-ca
