apiVersion: v1
kind: Service
metadata:
  name: adguard-home-headless
  namespace: adguard
  labels:
    app.kubernetes.io/name: adguard-home
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: adguard-home
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
