apiVersion: v1
kind: Service
metadata:
  name: adguard-home
  namespace: adguard
  labels:
    app.kubernetes.io/name: adguard-home
spec:
  type: LoadBalancer
  loadBalancerClass: io.cilium/l2-announcer
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: adguard-home
  ports:
    - name: dns-udp
      port: 53
      targetPort: dns
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: dns-tcp
      protocol: TCP
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    - name: setup
      port: 3000
      targetPort: setup
      protocol: TCP
