apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: adguard-home
  namespace: adguard
  labels:
    app.kubernetes.io/name: adguard-home
spec:
  serviceName: adguard-home-headless
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: adguard-home
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  template:
    metadata:
      labels:
        app.kubernetes.io/name: adguard-home
    spec:
      terminationGracePeriodSeconds: 10
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 30
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 30
      containers:
        - name: adguard-home
          image: adguard/adguardhome:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: dns
              containerPort: 53
              protocol: UDP
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: http
              containerPort: 80
              protocol: TCP
            - name: setup
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /opt/adguardhome/work
              subPath: work
            - name: data
              mountPath: /opt/adguardhome/conf
              subPath: conf
          startupProbe:
            exec:
              command: ['/bin/sh', '-c', 'pidof AdGuardHome >/dev/null 2>&1']
            periodSeconds: 5
            failureThreshold: 30
          livenessProbe:
            exec:
              command: ['/bin/sh', '-c', 'pidof AdGuardHome >/dev/null 2>&1']
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            exec:
              command: ['/bin/sh', '-c', 'pidof AdGuardHome >/dev/null 2>&1']
            periodSeconds: 5
            failureThreshold: 3
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
      spec:
        accessModes: ['ReadWriteOnce']
        storageClassName: longhorn-adguard-wffc
        resources:
          requests:
            storage: 5Gi
