apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-backup-truenas-s3
  namespace: longhorn-system
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: azure-kv-homelab
    kind: ClusterSecretStore
  target:
    name: longhorn-backup-truenas-s3 # <- the Secret Longhorn will read
    creationPolicy: Owner
    template:
      type: Opaque
  dataFrom:
    - extract:
        key: longhorn-backup-truenas-s3 # <- the Azure KV secret name from step 2
