apiVersion: v1
kind: Service
metadata:
  name: unifi
  namespace: net
  labels: { app: unifi }
spec:
  selector: { app: unifi }
  clusterIP: None
  ports:
    - { name: webapi, port: 8443, targetPort: 8443, protocol: TCP }
    - { name: inform, port: 8080, targetPort: 8080, protocol: TCP }
    - { name: stun, port: 3478, targetPort: 3478, protocol: UDP }
    - { name: discovery, port: 10001, targetPort: 10001, protocol: UDP }
    - { name: portal-https, port: 8843, targetPort: 8843, protocol: TCP }
    - { name: portal-http, port: 8880, targetPort: 8880, protocol: TCP }
