apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-unifi
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  numberOfReplicas: '2'
  staleReplicaTimeout: '2880'
