apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguard-home
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '30'
spec:
  project: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: adguard
  source:
    repoURL: https://github.com/greg-court/homelab.git
    targetRevision: main
    path: k8s/gitops/apps/adguard-home/overlays/klab
  ignoreDifferences:
    - kind: Service
      namespace: adguard
      jqPathExpressions:
        - .spec.clusterIP
        - .spec.clusterIPs
        - .spec.healthCheckNodePort
        - .spec.ipFamilies
        - .spec.ipFamilyPolicy
        - .spec.sessionAffinity
        - .spec.ports[].nodePort
        - .status
    - kind: StatefulSet
      namespace: adguard
      jqPathExpressions:
        - .spec.template.spec.dnsPolicy
        - .spec.template.spec.restartPolicy
        - .spec.template.spec.schedulerName
        - .spec.template.spec.securityContext
        - .spec.template.spec.containers[].resources
        - .spec.template.spec.containers[].terminationMessagePath
        - .spec.template.spec.containers[].terminationMessagePolicy
        - .status
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - PruneLast=true
