apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: binfmt
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: '24' } # before BuildKit (25)
spec:
  project: apps
  destination:
    namespace: gh-runners
  source:
    repoURL: https://github.com/greg-court/homelab.git
    targetRevision: main
    path: k8s/gitops/apps/binfmt/overlays/klab
