apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runners
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '22'
spec:
  project: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: gh-runners
  sources:
    # 1) Make sure arc-system namespace is labeled first
    - repoURL: https://github.com/greg-court/homelab.git
      targetRevision: main
      path: k8s/gitops/apps/gh-arc/arc-system-namespace

    # Ansible scale set
    - repoURL: ghcr.io/actions/actions-runner-controller-charts
      chart: gha-runner-scale-set
      targetRevision: '0.12.1'
      helm:
        releaseName: arc-ansible
        valueFiles:
          - $values/k8s/gitops/apps/gh-arc/values/common.yaml
          - $values/k8s/gitops/apps/gh-arc/values/ansible.yaml

    # Docker scale set
    - repoURL: ghcr.io/actions/actions-runner-controller-charts
      chart: gha-runner-scale-set
      targetRevision: '0.12.1'
      helm:
        releaseName: arc-docker
        valueFiles:
          - $values/k8s/gitops/apps/gh-arc/values/common.yaml
          - $values/k8s/gitops/apps/gh-arc/values/docker.yaml

    # Terraform scale set
    - repoURL: ghcr.io/actions/actions-runner-controller-charts
      chart: gha-runner-scale-set
      targetRevision: '0.12.1'
      helm:
        releaseName: arc-terraform
        valueFiles:
          - $values/k8s/gitops/apps/gh-arc/values/common.yaml
          - $values/k8s/gitops/apps/gh-arc/values/terraform.yaml

    # Packer scale set
    - repoURL: ghcr.io/actions/actions-runner-controller-charts
      chart: gha-runner-scale-set
      targetRevision: '0.12.1'
      helm:
        releaseName: arc-packer
        valueFiles:
          - $values/k8s/gitops/apps/gh-arc/values/common.yaml
          - $values/k8s/gitops/apps/gh-arc/values/packer.yaml

    # values ref so the $values/â€¦ paths resolve
    - repoURL: https://github.com/greg-court/homelab.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - PruneLast=true
