apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: runners-common
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: '-30' }
spec:
  project: apps
  destination:
    namespace: gh-runners
  source:
    repoURL: https://github.com/greg-court/homelab.git
    targetRevision: main
    path: k8s/gitops/apps/gh-runners-common/overlays/klab
