apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - binfmt.yaml
  - buildkit.yaml
  - ddclient.yaml
  - debug.yaml
  - gh-arc-runners.yaml
  - gh-runners-common.yaml
  - netbird-dmz.yaml
  - netbird-fam.yaml
  - netbird-greg.yaml
  - netbird-namespace.yaml
  - nginx-favicons.yaml
  - tfc-agents.yaml
