apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netbird-namespace
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: '-30' }
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: default # irrelevant; Namespace is cluster-scoped
  source:
    repoURL: https://github.com/greg-court/homelab.git
    targetRevision: main
    path: k8s/gitops/apps/netbird/namespace
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - PruneLast=true
