apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-favicons
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: '30' }
spec:
  project: apps
  destination: { server: https://kubernetes.default.svc, namespace: web }
  source:
    repoURL: https://github.com/greg-court/homelab.git
    targetRevision: main
    path: k8s/gitops/apps/nginx-favicons/overlays/klab
