apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tfc-agents
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: '25' }
spec:
  project: apps
  destination:
    namespace: tfc-agents
  source:
    repoURL: https://github.com/greg-court/homelab.git
    targetRevision: main
    path: k8s/gitops/apps/tfc-agents/overlays/klab
