apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unifi
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: '30' }
spec:
  project: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: unifi
  source:
    repoURL: https://github.com/greg-court/homelab.git
    targetRevision: main
    path: k8s/gitops/apps/unifi/overlays/klab
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - PruneLast=true
  ignoreDifferences: # prevent drift causing OutOfSync
    - group: apps
      kind: StatefulSet
      name: unifi
      namespace: unifi
      jqPathExpressions:
        - .spec.persistentVolumeClaimRetentionPolicy
        - .spec.template.spec.terminationGracePeriodSeconds
        - .spec.template.spec.restartPolicy
        - .spec.template.spec.schedulerName
        - .spec.template.spec.containers[] | select(.name=="controller").livenessProbe.successThreshold
        - .spec.template.spec.containers[] | select(.name=="controller").readinessProbe.successThreshold
        - .spec.template.spec.containers[] | select(.name=="controller").terminationMessagePath
        - .spec.template.spec.containers[] | select(.name=="controller").terminationMessagePolicy
        - .spec.template.spec.containers[] | select(.name=="controller").env[] | select(.name=="SYSTEM_IP").valueFrom.fieldRef.apiVersion
        - .spec.volumeClaimTemplates[].spec.volumeMode
        - .spec.volumeClaimTemplates[].apiVersion
        - .spec.volumeClaimTemplates[].kind
        - .spec.volumeClaimTemplates[].status
