apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: config-backups-env
  namespace: unifi
  annotations: { argocd.argoproj.io/sync-wave: '-1' }
spec:
  refreshInterval: 12h
  secretStoreRef: { name: azure-kv-homelab, kind: ClusterSecretStore }
  target:
    name: config-backups-env
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: config-backups
