apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: unifi
resources:
  - externalsecret.yaml
  - configmap.yaml
  - cronjob.yaml
configMapGenerator:
  - name: homelab-ca
    files:
      - homelab-ca.crt=../../../certs/homelab-ca.crt
generatorOptions:
  disableNameSuffixHash: true
