apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-storage-namespace
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '-29'
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: local-path-storage
  source:
    repoURL: https://github.com/greg-court/homelab.git
    targetRevision: main
    path: k8s/gitops/charts/namespace-privileged
    helm:
      values: |
        name: local-path-storage
        labels:
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/audit: baseline
          pod-security.kubernetes.io/warn: baseline
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
