apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: local-path-storage
  source:
    repoURL: https://github.com/rancher/local-path-provisioner
    targetRevision: v0.0.32
    path: deploy/helm/local-path-provisioner
    helm:
      values: |
        storageClass:
          name: local-path
          defaultClass: false
          reclaimPolicy: Delete
          volumeBindingMode: WaitForFirstConsumer

        # Talos-friendly writable path
        nodePath: /var/local-path-provisioner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
