apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-backup-truenas-s3
  namespace: longhorn-system
  annotations:
    # make sure it lands before/with Longhorn
    argocd.argoproj.io/sync-wave: '-29'
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: azure-kv-homelab
    kind: ClusterSecretStore
  target:
    name: longhorn-backup-truenas-s3
    creationPolicy: Owner
    template:
      type: Opaque
  dataFrom:
    - extract:
        key: longhorn-backup-truenas-s3
