apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: daily-backup
  namespace: longhorn-system
spec:
  cron: '0 2 * * *' # 02:00 daily
  task: 'backup'
  retain: 14
  concurrency: 2
  parameters:
    full-backup-interval: '30'
  groups: ['default']
