apiVersion: longhorn.io/v1beta2
kind: BackupTarget
metadata:
  name: default
  namespace: longhorn-system
  annotations:
    # apply after the Longhorn chart (-28) so the CRD exists
    argocd.argoproj.io/sync-wave: '-27'
spec:
  backupTargetURL: s3://longhorn@minio/
  credentialSecret: longhorn-backup-truenas-s3
  pollInterval: 300s
