apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: '-28' }
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.9.1
    helm:
      values: |
        # Make Longhorn the default StorageClass *now*
        persistence:
          defaultClass: true
          defaultClassReplicaCount: 2

        # Longhorn cluster defaults
        defaultSettings:
          defaultReplicaCount: 2
          backupTarget: "s3://longhorn@minio/"
          backupTargetCredentialSecret: "longhorn-backup-truenas-s3"
          backupstorePollInterval: 300

        # Expose UI only on VLAN 3 via Traefik "trust" ingress class
        ingress:
          enabled: true
          ingressClassName: trust
          host: longhorn.apps.klab.internal
          tls: true
          tlsSecret: longhorn-tls
          annotations:
            cert-manager.io/cluster-issuer: homelab-ca

        # Let Prometheus Operator (KPS) scrape Longhorn
        metrics:
          serviceMonitor:
            enabled: true

        preUpgradeChecker:
          jobEnabled: false
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - PruneLast=true
