apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '-14' # before apps
spec:
  project: platform
  destination:
    namespace: arc-system
  source:
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    chart: gha-runner-scale-set-controller
    targetRevision: '0.12.1'
    helm:
      values: |
        controllerManager:
          metrics:
            addr: ":8080"

      - PruneLast=true
      - ApplyOutOfSyncOnly=true
