apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - projects/platform.yaml
  - projects/apps.yaml
  - argocd/arc-controller.yaml
  - argocd/arc-helm-oci-repo.yaml
  - argocd/argocd-cm.yaml
  - argocd/expose-argocd.yaml
  - security/cert-manager.yaml
  - security/cert-issuers.yaml
  - security/external-secrets-operator.yaml
  - security/letsencrypt-dns.yaml
  - networking/cilium/cilium-egress.yaml
  - networking/cilium/cilium-lb.yaml
  - networking/expose-hubble.yaml
  - networking/ingress/traefik/traefik-crds.yaml
  - networking/ingress/traefik/traefik-trust.yaml
  - networking/ingress/traefik/traefik-dmz.yaml
  - networking/vip-pbr.yaml
  - storage/local-path-provisioner.yaml
  - storage/longhorn-namespace.yaml
  - storage/longhorn.yaml
  - monitoring/monitoring-namespace.yaml
  - monitoring/metrics-server.yaml
  - monitoring/kube-prometheus-stack.yaml
  - monitoring/loki.yaml
  - monitoring/kps-extras.yaml
  - monitoring/alloy.yaml
